//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string NIC { get; set; }
        public string Notes { get; set; }
        public Nullable<long> DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
